export const ADVERTISEMENTS_REQUEST = 'ADVERTISEMENTS_REQUEST';
export const ADVERTISEMENTS_SUCCESS = 'ADVERTISEMENTS_SUCCESS';
export const ADVERTISEMENTS_FAILURE = 'ADVERTISEMENTS_FAILURE';

export const AD_REQUEST = 'AD_REQUEST';
export const AD_SUCCESS = 'AD_SUCCESS';
export const AD_FAILURE = 'AD_FAILURE';

export const AD_CREATION_REQUEST = 'AD_CREATION_REQUEST';
export const AD_CREATION_SUCCESS = 'AD_CREATION_SUCCESS';
export const AD_CREATION_FAILURE = 'AD_CREATION_FAILURE';

export const AD_DELETION_REQUEST = 'AD_DELETION_REQUEST';
export const AD_DELETION_SUCCESS = 'AD_DELETION_SUCCESS';
export const AD_DELETION_FAILURE = 'AD_DELETION_FAILURE';


export const TAGS_REQUEST = 'TAGS_REQUEST';
export const TAGS_SUCCESS = 'TAGS_SUCCESS';
export const TAGS_FAILURE = 'TAGS_FAILURE';

export const AUTHENTICATION_LOGIN_REQUEST = 'AUTHENTICATION_LOGIN_REQUEST';
export const AUTHENTICATION_LOGIN_SUCCESS = 'AUTHENTICATION_LOGIN_SUCCESS';
export const AUTHENTICATION_LOGIN_FAILURE = 'AUTHENTICATION_LOGIN_FAILURE';

export const AUTHENTICATION_LOGOUT_SUCCESS = 'AUTHENTICATION_LOGOUT_SUCCESS';

export const UI_RESET_ERROR = 'UI_RESET_ERROR';